version: '3.9'

services:

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: invoice_db
      MYSQL_ROOT_PASSWORD: S3cret
      MYSQL_PASSWORD: An0thrS3crt
      MYSQL_USER: invoice_db_user
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
    db_data: